version: '3.8'
services:
    php-apache:
        container_name: php-apache
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        #      args:
        #          CONTAINER_DOMAIN: ${CONTAINER_DOMAIN}
#        environment:
#            - CONTAINER_DOMAIN=${CONTAINER_DOMAIN}
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html/
            - ./.docker/apache2/conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "80:80"
        working_dir: /var/www/html/
        networks:
            - 'global'

    composer:
        container_name: composer
        image: composer:latest
        volumes:
            - .:/var/www/html/
        working_dir: /var/www/html/
        command: composer install
        networks:
            - 'global'

    mysql:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "9906:3306"
        volumes:
            - ./.docker/mount/database/mysql:/var/lib/mysql
        networks:
            - 'global'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
        networks:
            - 'global'

    rabbitmq:
        image: rabbitmq:3.12-management
        container_name: rabbitmq-management
        ports:
            - "5672:5672" # Cổng AMQP
            - "15672:15672" # Cổng giao diện quản lý
        environment:
            RABBITMQ_DEFAULT_USER: rabbitusr
            RABBITMQ_DEFAULT_PASS: rabbitpw
        volumes:
            - ./.docker/mount/rabbitmq:/var/lib/rabbitmq  # Lưu trữ dữ liệu RabbitMQ
        networks:
            - 'global'

    redis:
        image: redis/redis-stack:latest
        container_name: redis
        ports:
            - "6379:6379"
            - "8001:8001"
        volumes:
            - ./.docker/mount/redis:/data
            - ./.docker/redis/redis.conf:/etc/redis.conf
        networks:
            - 'global'

    redis-exporter:
        image: bitnami/redis-exporter
        container_name: redis-exporter
        ports:
            - "9121:9121"
        networks:
            - 'global'
        command:
            - '--redis.addr=redis://redis:6379'

    mongodb-server:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb-server
        ports:
            - "27017:27017"
        volumes:
            - ./.docker/mount/database/mongodb/db:/data/db
            - ./.docker/mount/database/mongodb/configdb:/data/configdb
        environment:
            MONGODB_INITDB_ROOT_USERNAME: mongours
            MONGODB_INITDB_ROOT_PASSWORD: mongopw
        networks:
            - 'global'

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: always
        ports:
            - "9090:9090"
        volumes:
            - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - 'global'

networks:
    global:
        driver: bridge
